# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Packer"

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "20 04 1,15 * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-packer:
    name: "Validate Packer configuration"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: "read"
    defaults:
      run:
        working-directory: "./packer/"
    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v4"
      - name: "Install dependencies"
        run: |
          curl --proto '=https' --tlsv1.3 -sSf 'https://apt.releases.hashicorp.com/gpg' | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/hashicorp.gpg
          printf '%s\n' "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list >/dev/null
          sudo apt-get update && sudo apt-get install -y --no-install-recommends packer
      - name: "Init Packer"
        run: |
          packer init ./
      - name: "Validate configuration"
        run: |
          packer validate ./
      - name: "Check configuration format"
        run: |
          packer fmt -check -diff ./

  build-packer:
    name: "Build Packer image"
    needs: ["validate-packer"]
    runs-on: "ubuntu-24.04"
    permissions:
      contents: "read"
    defaults:
      run:
        working-directory: "./packer/"
    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v4"
      - name: "Install dependencies"
        run: |
          curl --proto '=https' --tlsv1.3 -sSf 'https://apt.releases.hashicorp.com/gpg' | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/hashicorp.gpg
          printf '%s\n' "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list >/dev/null
          sudo apt-get update && sudo apt-get install -y --no-install-recommends packer qemu-utils qemu-system-x86
      - name: "Init Packer"
        run: |
          packer init ./
      - name: "Build image"
        run: |
          sudo make build-armhf PACKER_LOG=1
